qdrant:
  url: http://localhost:6333
  default_collection: my_documents

embedding:
  backend: ollama
  ollama_url: http://localhost:11434
  model_name: bge-m3:latest
  embedding_dim: 1024

paths:
  input_dir: ./input
